version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source code dependencies...
      - npm install
  build:
    commands:
      - echo Building application...
      - npm run build

artifacts:
  base-directory: build
  files:
    - '**/*'
