import { useEffect } from "react";
import Panel from "../UI/Panel";

export default function TermsPage() {
  
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <Panel>
      <div style={{ textAlign: "center" }}>
        <h1>Terms and Conditions of Use</h1>
        <div style={{ textAlign: "justify", marginTop: "3rem", padding: "2%" }}>
          <h2>1. General Information</h2>
          <p>
            The App uses artificial intelligence and machine learning
            technologies to generate stories, images and audio files based on
            the prompts provided by the user. The App does not guarantee the
            accuracy or completeness of the output generated by these
            technologies. The user is responsible for evaluating the output and
            determining its suitability for their needs.
          </p>
          <h2>2. Intellectual Property</h2>
          <p>
            The App is the intellectual property of its owner and is protected
            by copyright and other intellectual property laws. The user agrees
            not to copy, modify, distribute, or create derivative works based on
            the App without the owner's express permission.
          </p>
          <h2>3. User Content</h2>
          <p>
            The user is solely responsible for the content they submit to the
            App, including the prompts they provide and the output generated by
            the App. The user represents and warrants that their content does
            not infringe any intellectual property or other proprietary rights
            of third parties.
          </p>
          <h2>4. Misuse of Generated Content</h2>
          <p>
            Users are not permitted to use the generated content for illegal
            activities, including but not limited to harassment, hate speech,
            discrimination, or any other activities that may cause harm to
            others. Additionally, users are not allowed to use the generated
            content for commercial purposes, such as selling or distributing the
            content for profit without obtaining the necessary permissions and
            licenses. Any violation of these terms may result in the termination
            of user access to the app and legal action if deemed necessary.
          </p>
          <h2>5. Use of Data</h2>
          <p>
            The App collects and uses data in accordance with its Privacy
            Policy. The user agrees to the collection and use of their data in
            accordance with the Privacy Policy.
          </p>
          <h2>6. Disclaimer</h2>
          <p>
            The App is provided on an "as is" basis, without warranties of any
            kind, express or implied. The owner of the App makes no
            representation or warranty that the App will meet the user's
            requirements or be uninterrupted, timely, secure, or error-free. The
            owner of the App will not be liable for any direct, indirect,
            incidental, consequential, or punitive damages arising out of the
            use or inability to use the App.
          </p>
          <h2>7. Modification</h2>
          <p>
            The owner of the App reserves the right to modify these Terms of Use
            at any time. The user's continued use of the App after such
            modifications shall constitute their acceptance of the modified
            Terms of Use.
          </p>
        </div>
      </div>
    </Panel>
  );
}
